### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by maverick74** [nekoziroo/Text-Link-webext#1]
OS: openSUSE (linux)
FF: 53.0.3 (64bit)

**Text Link WE 1.3** addon does not work at all.

**Text Link webext 1.0.1** addon is working, but it only does so when address are started by **http**. If they are started by **www** or have no **http** or **www** it does not work at all. 

I double click links and they just do not open...

**Comment by nekoziroo** [comment]
I am thinking how to make it work.

**Comment by maverick74** [comment]
Great!

One question: is Text Link webext really meant to replace Text Link WE?

**Comment by nekoziroo** [comment]
Yes.

**Comment by maverick74** [comment]
OK, i was asking this because version number from Text Link WE may lead users to think that it is advanced...

About a way to make it work: it may be worth taking a look at Pyro's Text Link... :)

**Comment by nekoziroo** [comment]
I made it work with version 1.0.3

**Comment by maverick74** [comment]
Thank you :)
