### ISSUE TITLE
Addon does not reconise 2 letter domains

### ISSUE THREAD

**Issue by maverick74** [nekoziroo/Text-Link-webext#4]
URL's such as google.es do not work (google.com does, however).

**Comment by nekoziroo** [comment]
It worked on my pc. I searched for google.it, google.sk, google.no. What is the language of your firefox and google?

**Comment by maverick74** [comment]
pt-pt

**Comment by nekoziroo** [comment]
I changed the languages of firefox and google to pt-pt, but it still worked. What URL did you click?

**Comment by nekoziroo** [comment]
I fixed it because I found a bug. try to work.

**Comment by maverick74** [comment]
It seems it's working fine now

:D 

Thanks
