### ISSUE TITLE
Recognition for the URL including Japanese,Koreans,Chinese,etc (Enhancement)

### ISSUE THREAD

**Issue by roflsunriz** [nekoziroo/Text-Link-webext#5]
For example, if you meet the URL such as "**テスト.com**" or "**테스트.com**" or **"測試.com**" etc. the extension do absolutely nothing.
Or,"**www.example.com/テスト.html**",... etc

URLを抽出する正規表現はどう書くべきか
http://d.hatena.ne.jp/sutara_lumpur/20100827/1282872312
> **/(?:^|[\s　]+)((?:https?|ftp):\/\/[^\s　]+)/**

日本語を含む URL にマッチする正規表現 · GitHub
https://gist.github.com/kawanet/61d9ab15f9bdaaeb20a7
>**/(https?:\/\/[\w\-\.\/\?\,\#\:\u3000-\u30FE\u4E00-\u9FA0\uFF01-\uFFE3]+)/**

**Comment by nekoziroo** [comment]
#### http://日本語.jp/
二つの正規表現を試してみたがうまく動作しませんでした。
#### 正規表現
```javascript
/(?:^|[\s　]+)((?:https?|ftp):\/\/[^\s　]+)/
```
```javascript
/(https?:\/\/[\w\-\.\/\?\,\#\:\u3000-\u30FE\u4E00-\u9FA0\uFF01-\uFFE3]+)/
```
"http://日本語.jp/" のように"http://"から始まる場合は、URLだと判別できる。
しかし、"テキストリンク日本語.jp/" のように日本語に続けて書いてある日本語URLは、判別できずに誤作動を起こすと思います。なので"http://"から始まらない日本語などのURLに対応するのは難しいと思う。

**Comment by roflsunriz** [comment]
日本語を含む２バイト文字用URL正規表現
regexp string:**(?:[a-z]{1,4})?[\W]+\.[a-z]{1,2}(?:\/)?[\W\w]+**
test string:**あいうえお.jp/あかさたな.html**

_(いっその事正規表現を一本化せずに二本作って二本走らせるとか)_
